before_script:
  - bundle_install

stages:
  - build

verify:
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y arduino arduino-core
    - arduino --verify /build/jaflo/wordaround/wordaround.ino
  only:
    - master
