image: pandrew/arduino:latest

before_script:
  - bundle_install

stages:
  - build

verify:
  stage: build
  script:
    - arduino --verify /build/jaflo/wordaround/wordaround.ino
  only:
    - master